name: main CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x  # Use your desired Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install numpy  
        python -m pip install scipy

    - name: Run tests
      run: |
        python -m unittest discover -s main/Test -p '__init__.py' -t main
